Repository LaOuede/42-ft_transcendence, pull requests merged in 2024-05, with the labels that each got.

#83 Fix user delete loop
  transcendence/user/views.py
Labels: bugfix

#84 Feat/user status
  transcendence/base/static/js/auth.js
  transcendence/base/static/js/friends.js
  transcendence/base/static/js/nav.js
  transcendence/base/static/js/notifications.js
  transcendence/base/static/js/websocket.js
  transcendence/base/static/styles/friends.css
  transcendence/base/static/styles/notifications.css
  transcendence/base/templates/base.html
  transcendence/custom_auth/migrations/0001_initial.py
  transcendence/custom_auth/services.py
  transcendence/friends/consumers.py
  transcendence/friends/migrations/0002_initial.py
  transcendence/friends/models.py
  transcendence/friends/templates/friends/list.html
  transcendence/friends/templatetags/__init__.py
  transcendence/friends/templatetags/custom_filters.py
  transcendence/friends/urls.py
  transcendence/friends/utils.py
  transcendence/friends/views.py
  transcendence/games_history/migrations/0002_initial.py
  transcendence/middleware/jwt_authentication_middleware.py
  transcendence/middleware/ws_auth_middleware.py
  transcendence/tools/test.py
  transcendence/transcendence/asgi.py
  transcendence/transcendence/settings.py
  transcendence/user/serializers.py
  transcendence/user/views.py
Labels: enhancement

#86 changes to settings error messages: popup and translations
  transcendence/base/locale/es/LC_MESSAGES/django.mo
  transcendence/base/locale/es/LC_MESSAGES/django.po
  transcendence/base/locale/fr/LC_MESSAGES/django.mo
  transcendence/base/locale/fr/LC_MESSAGES/django.po
  transcendence/base/static/js/api.js
  transcendence/base/static/js/settings.js
  transcendence/base/static/js/translation/dictionnary.js
  transcendence/base/static/styles/notifications.css
  transcendence/transcendence/settings.py
  transcendence/user/serializers.py
  transcendence/user/tests.py
  transcendence/user/views.py
Labels: enhancement

#87 plus facile changer les controls
  transcendence/base/static/js/pong/pong.js
Labels: enhancement

#88 Game history
  transcendence/base/locale/es/LC_MESSAGES/django.mo
  transcendence/base/locale/es/LC_MESSAGES/django.po
  transcendence/base/locale/fr/LC_MESSAGES/django.mo
  transcendence/base/locale/fr/LC_MESSAGES/django.po
  transcendence/base/static/js/auth.js
  transcendence/base/static/js/friends.js
  transcendence/base/static/js/notifications.js
  transcendence/base/static/js/pong/pong.js
  transcendence/base/static/js/pong/pong_var.js
  transcendence/base/static/js/pong/tournament.js
  transcendence/base/static/js/translation/dictionnary.js
  transcendence/base/static/js/websocket.js
  transcendence/base/static/styles/index.css
  transcendence/base/templates/profile.html
  transcendence/base/templates/settings.html
  transcendence/custom_auth/migrations/0001_initial.py
  transcendence/custom_auth/migrations/0002_otpsession_user.py
  transcendence/friends/migrations/0001_initial.py
  transcendence/friends/migrations/0002_initial.py
  transcendence/friends/models.py
  transcendence/friends/templates/friends/list.html
  transcendence/friends/utils.py
  transcendence/friends/views.py
  transcendence/games_history/admin.py
  transcendence/games_history/migrations/0001_initial.py
  transcendence/games_history/migrations/0002_initial.py
  transcendence/games_history/migrations/0003_alter_game_game_type.py
  transcendence/games_history/models.py
  transcendence/games_history/serializers.py
  transcendence/games_history/templates/games_history/history.html
  transcendence/games_history/templates/games_history/stats.html
  transcendence/games_history/views.py
  transcendence/locale/es/LC_MESSAGES/django.mo
  transcendence/locale/es/LC_MESSAGES/django.po
  transcendence/locale/fr/LC_MESSAGES/django.mo
  transcendence/locale/fr/LC_MESSAGES/django.po
  transcendence/transcendence/settings.py
  transcendence/user/migrations/0001_initial.py
  transcendence/user/views.py
Labels: enhancement, bugfix

#89 Daphne and translations
  docker-compose.yml
  nginx/conf/default.conf
  transcendence/base/static/js/auth.js
  transcendence/base/static/js/friends.js
  transcendence/base/static/js/translation/chooseLanguage.js
  transcendence/base/static/js/translation/dictionnary.js
  transcendence/base/static/js/websocket.js
  transcendence/friends/consumers.py
  transcendence/friends/models.py
  transcendence/friends/templates/friends/index.html
  transcendence/friends/utils.py
  transcendence/friends/views.py
  transcendence/games_history/migrations/0003_alter_game_game_type.py
  transcendence/locale/es/LC_MESSAGES/django.mo
  transcendence/locale/es/LC_MESSAGES/django.po
  transcendence/locale/fr/LC_MESSAGES/django.mo
  transcendence/locale/fr/LC_MESSAGES/django.po
  transcendence/middleware/ws_auth_middleware.py
  transcendence/tools/entrypoint.sh
  transcendence/transcendence/asgi.py
  transcendence/transcendence/settings.py
  transcendence/user/views.py
Labels: enhancement, bugfix

#90 Bugfix/translation
  transcendence/base/static/js/pong/pong.js
  transcendence/base/static/js/translation/chooseLanguage.js
  transcendence/friends/consumers.py
  transcendence/friends/utils.py
  transcendence/games_history/admin.py
  transcendence/games_history/tests.py
  transcendence/games_history/urls.py
  transcendence/games_history/views.py
  transcendence/locale/fr/LC_MESSAGES/django.mo
  transcendence/locale/fr/LC_MESSAGES/django.po
  transcendence/transcendence/settings.py
  transcendence/transcendence/urls.py
  transcendence/user/migrations/0002_user_current_language.py
  transcendence/user/models.py
  transcendence/user/serializers.py
  transcendence/user/views.py
Labels: enhancement, bugfix
